main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('poke/', views.poke_index, name='index'),
  path('poke/new/', views.new, name='new'),
  path('poke/<int:poke_id>/', views.show, name='show'),
  path('poke/submit/', views.submit, name='submit'),
  path('poke/<int:poke_id>/edit', views.edit, name='edit'),
  path('poke/<int:poke_id>/update', views.update, name='update'),
  path('poke/<int:poke_id>/delete', views.delete, name='delete'),
  path('poke/<int:poke_id>/add_photo/', views.add_photo, name='add_photo'),
  path('poke/<int:poke_id>/add_item', views.add_item, name="add_item"),
  path('poke/<int:poke_id>/add_attack/<int:attack_id>', views.ass_attack, name="ass_attack"),
  path('attack/new', views.new_attack, name="new_attack"),
  path('attack/submit', views.add_attack, name="add_attack")

]

pokecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models

# Create your models here.

class Attack(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)

    def __str__(self):
      return self.name


class Poke(models.Model):
    name = models.CharField(max_length=100)
    poke_type = models.CharField(max_length=100)
    attack = models.ManyToManyField(Attack)
    level = models.IntegerField()

    def __str__(self):
        return self.name
        

class Item(models.Model):
  name = models.CharField(max_length=100)
  poke = models.ForeignKey(Poke, on_delete=models.CASCADE)

  def __str__(self):
      return self.name

class Photo(models.Model):
    url = models.CharField(max_length=200)
    poke = models.ForeignKey(Poke, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for poke_id: {self.poke_id} @{self.url}"

main_app/views.py
from django.shortcuts import render, redirect
from .models import Poke

from django.http import HttpResponse

import uuid
import boto3
from .models import Poke, Item, Photo, Attack

S3_BASE_URL = 'https://s3.ca-central-1.amazonaws.com/'
BUCKET = 'pokecollector'

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def poke_index(request):
  poke = Poke.objects.all()
  return render(request, 'poke/index.html', { 'poke': poke })

def show(request,poke_id):
  pokemon = Poke.objects.get(id=poke_id)
  attacks = Attack.objects.exclude(id__in = pokemon.attack.all().values_list('id'))
  return render(request, 'poke/show.html', {'pokemon': pokemon, 'attacks': attacks})

def new(request):
  return render(request, 'poke/new.html')

def submit(request):
  poke = Poke.objects.create(
    name=request.POST['name'],
    poke_type=request.POST['type'],
    attack=request.POST['attack'],
    level=request.POST['level']
    )
  return redirect('/poke')

def edit(request, poke_id):
  poke = Poke.objects.get(id=poke_id)
  return render(request, 'poke/edit.html', {'poke': poke})

def update(request, poke_id):
    poke = Poke.objects.get(id=poke_id)
    poke.name=request.POST['name']
    poke.poke_type=request.POST['type']
    poke.attack=request.POST['attack']
    poke.level=request.POST['level']
    poke.save()
    return redirect(f'/poke/{poke_id}')
  
def delete(request, poke_id):
  Poke.objects.filter(id=poke_id).delete()
  return redirect('/poke')

def add_photo(request, poke_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            photo = Photo(url=url, poke_id=poke_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect(f'/poke/{poke_id}')

def add_item(request, poke_id):
  item = Item.objects.create(
    name=request.POST['item'],
    poke=Poke.objects.get(id=poke_id)
    )
  return redirect(f'/poke/{poke_id}')

def ass_attack(request, poke_id, attack_id):
  Poke.objects.get(id=poke_id).attack.add(attack_id)
  return redirect(f'/poke/{poke_id}')

def new_attack(request):
  attacks = Attack.objects.all()
  return render(request, 'poke/new_attack.html', {'attacks': attacks})

def add_attack(request):
  attack = Attack.objects.create(
    name=request.POST['name'],
    type=request.POST['type']
    )
  return redirect('/attack/new')

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Poke Collector</h1>
<hr />
<p>Hire the Poke Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Poke Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;PokeCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
          <li><a href="/poke">View All My Poke</a></li>
          <li><a href="/poke/new">Add New Pokemon</a></li>
          <li><a href="/attack/new">Add New Attack</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Poke Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>HOME</h1>


{% endblock %}

main_app/templates/poke/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="/poke/{{ poke.id }}/update">
    {% csrf_token %}

    Name: <input name="name" value="{{ poke.name }}">
    Type: <input name="type" value="{{ poke.poke_type }}" >
    Attack: <input name="attack" value="{{ poke.attack }}">
    Level: <input name="level" type="number" value="{{ poke.level }}" >
    
    <button type="submit">Update</button>
</form>
{% endblock %}

main_app/templates/poke/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Poke List</h1>

{% for pokemon in poke %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ pokemon.name }}</span>
      <p>Type: {{ pokemon.poke_type }}</p>
      <p>Attack: {{ pokemon.attack }}</p>
      {% if pokemon.level > 0 %}
        <p>Level: {{ pokemon.level }}</p>
      {% else %}
        <p>Level: Baby</p>
      {% endif %}
    </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/poke/new.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="/poke/submit/">
    {% csrf_token %}
    Name: <input name="name">
    Type: <input name="type">
    Level: <input name="level">
    <button type="submit">Add</button>
</form>
{% endblock %}

main_app/templates/poke/new_attack.html
{% extends 'base.html' %}
{% block content %}
<h1>Add an attack:</h1>
<form method="POST" action="/attack/submit">
    {% csrf_token %}
    Name: <input name="name">
    Type: <input name="type">
    <button type="submit">Add</button>
</form>
<h1>All attacks:</h1>
{% for attack in attacks %}
    <div class="col s6">
      <div class="card">
        <p>Name: {{ attack.name }}</p>
        <p>Type: {{ attack.type }}</p>

      </div>
    </div>
    {% endfor %}

{% endblock %}

main_app/templates/poke/show.html
{% extends 'base.html' %}
{% block content %}

<h1>Poke Detail</h1>


<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ pokemon.name }}</span>
        <p>Type: {{ pokemon.poke_type }}</p>
        <p>Attack: {{ pokemon.attack }}</p>
        {% if pokemon.level > 0 %}
        <p>Level: {{ pokemon.level }}</p>
        {% else %}
        <p>Level: Baby</p>
        {% endif %}
      </div>
    </div>


    <a href="/poke/{{pokemon.id}}/edit">Edit</a> <br>
    <a href="/poke/{{pokemon.id}}/delete">Delete</a> <br>
    {% for photo in pokemon.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}

    <form action="{% url 'add_photo' pokemon.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
  </form>
  </div>
<div class="col s6">

  <div>
    <h4>Add Item</h4>
    <form action="/poke/{{pokemon.id}}/add_item" method="POST">
      {% csrf_token %}
      Item: <input name="item">
      <button type="submit">Add</button>
    </form>
  </div>

  <table class="striped">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      {% for item in pokemon.item_set.all %}
      <tr>
        <td>{{item.name}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ pokemon.name }}'s Attacks</h3>
    {% if pokemon.attack.count %}
      {% for attack in pokemon.attack.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <!-- A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }} -->
              <div>{{ attack.name }}</div>
              <h6>{{ attack.type }}</h6>
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Attacks :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->

  <div>
    <h3>Available Attacks</h3>
    {% for attack in attacks %}
    <div class="col s6">
      <div class="card">
        <p>Name: {{ attack.name }}</p>
        <p>Type: {{ attack.type }}</p>
        <form action="/poke/{{pokemon.id}}/add_attack/{{attack.id}}" method="POST">
          {% csrf_token %}
          <button>Add Attack</button>
        </form>

      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}